### ISSUE TITLE
Indentation Error: expected an indented block

### ISSUE THREAD

**Issue by paulkramme** [BendixBartsch/Chatbot#3]
Chatbot doesn't even start, instead it throws this exeption:
![qobjerror](https://cloud.githubusercontent.com/assets/19418956/16319248/b7f124ec-3992-11e6-8dea-81e7df4ed6c4.png)

**Comment by BendixBartsch** [comment]
downloaded "words.txt"?

**Comment by paulkramme** [comment]
Jup
